---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: file
  name: thumbnail
  label: thumbnail
- type: text
  name: year
  label: year
- type: list
  name: categories
  label: categories
  config:
    use_select: false
- name: gallery
  type: image_gallery
  config: {}
  label: Gallery
  description: Gallery text
pages:
- projects/molecular-gastronomy.md
- projects/the-london-book-fair.md
- projects/°-jupiter-calendar.md
